# Generated by Django 3.0.3 on 2020-05-05 13:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(editable=False)),
                ('datetime_operation', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(editable=False, max_length=50)),
                ('before_changes', jsonfield.fields.JSONField(blank=True, null=True)),
                ('after_changes', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
