# Generated by Django 3.0.3 on 2020-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisicmodel',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
