# Generated by Django 3.0.3 on 2020-04-27 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('head_uuid', models.UUIDField()),
                ('body', models.TextField()),
                ('parent', models.UUIDField(null=True)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('user_uuid', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
