# Generated by Django 3.0.3 on 2020-03-13 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_uuid', models.UUIDField()),
                ('header', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('views', models.PositiveIntegerField()),
                ('tags', models.ManyToManyField(to='api.TagModel')),
            ],
        ),
    ]
