# Generated by Django 3.0.3 on 2020-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200427_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentialsmodel',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
